name: r-ai
version: '3.7'
services:
  r-ai:
    build:  
      context: .
      dockerfile: env/Dockerfile
    stdin_open: true
    tty: true      
    volumes:
      - .:/code
    restart: always
    environment:
      USER: $R_STUDIO_USER
      PASSWORD: $R_STUDIO_PASSWORD
      ROOT: "TRUE"
      DISABLE_AUTH: "TRUE"      
    networks:
      -  default
    container_name: r_ai
    hostname: myhostname
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

